apiVersion: apps/v1
kind: Deployment
metadata:
  name: caduceus
  namespace: search-on-prem
  labels:
    app: caduceus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caduceus
  template:
    metadata:
      labels:
        app: caduceus
    spec:
      containers:
        - name: caduceus
          image: cr.cloud-preprod.yandex.net/crtioebhgqbfi2ae1pqd/caduceus:fff0a4d1a38f6b3d4f4c817c902737a20698c935.caduceus-fix
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          volumeMounts:
            - name: caduceus-data
              mountPath: /usr/disk/search/caduceus/data/
      volumes:
        - name: caduceus-data
          persistentVolumeClaim:
            claimName: csi-s3-pvc
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: caduceus
  name: caduceus
  namespace: search-on-prem
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: caduceus
  type: ClusterIP
