apiVersion: apps/v1
kind: Deployment
metadata:
  name: disk-search-proxy
  namespace: search-on-prem
  labels:
    app: disk-search-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disk-search-proxy
  template:
    metadata:
      labels:
        app: disk-search-proxy
    spec:
      containers:
        - name: disk-search-proxy
          image: cr.cloud-preprod.yandex.net/crtioebhgqbfi2ae1pqd/disk_search_proxy:94d84c641188777255d4d82ef99eb5a040746b4f.disk-search-proxy-on-docker
          imagePullPolicy: IfNotPresent
          env:
            - name: XMX
              value: "1G"
            - name: XMS
              value: "512M"
            - name: DJFS_HOST
              value: "caduceus.search-on-prem.svc.cluster.local"
            - name: PRODUCER_HOST
              value: "caduceus.search-on-prem.svc.cluster.local"
            - name: HTTPS_PORT
              value: "8080"
            - name: HTTP_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          volumeMounts:
            - name: search-map
              mountPath: /usr/disk/search/proxy/
      volumes:
        - name: search-map
          configMap:
            name: search-map-cm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: disk-search-proxy
  name: disk-search-proxy
  namespace: search-on-prem
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: caduceus
  type: ClusterIP
